import React from "react";

import {Row, Col } from "react-bootstrap";
import PricingCards from "../../Cards/PricingCards";
import { useNavigate } from "react-router-dom";
import "../Pricing/Pricing.css";
export default function Pricing() {
  const navigate= useNavigate()
  return (
    <div className="accent2 p-5">
      <header id="pricingHeader">
        {" "}
        <h3 id="pricingH3">Pricing</h3>
        <p>Choose a pricing plan that fits your needs</p>
      </header>

      <Row xs={1} md={3} id="parentRow" className="g-5">
        <Col className="pricingCols">
          <PricingCards
            title={"Basic"}
            borderID="blackBG"
            price={"$ 150"}
            features={[
              "10GB Storage",
              "25 Accounts",
              "AutoGenerated PDF's",
              "Endless Support",
            ]}
            handleSignUp={()=> navigate("/register")}
          />
        </Col>
        <Col className="pricingCols">
          <PricingCards
            title={"Pro"}
            customCssID={"proPlan"}
            borderID="featureBG"
            price={"$ 500"}
            features={[
              "50GB Storage",
              "100+ Accounts",
              "AutoGenerated PDF's",
              "AI Features",
            ]}
            handleSignUp={()=> navigate("/register")}
          />
        </Col>

        <Col className="pricingCols">
          <PricingCards
            title={"Premium"}
            borderID="blackBG"
            price={"$ 250"}
            features={[
              "20GB Storage",
              "50 Accounts",
              "AutoGenerated PDF's",
              "Endless Support",
            ]}
            handleSignUp={()=> navigate("/register")}
          />
        </Col>
      </Row>
    </div>
  );
}
